In [5]:
import os
import pandas as pd

In [6]:
def fix_file(path, to_path_base):
    frame = pd.read_csv(path, sep=' ', header=None, index_col=None)
    frame = frame.transpose().map(lambda p: os.path.basename(p))
    frame.to_csv(f'{to_path_base}_all.csv', header=None, index=False)
    train_size = (int)(len(frame) * 0.8)
    frame.head(train_size).to_csv(f'{to_path_base}_train.csv', header=None, index=False)
    frame.tail(len(frame) - train_size).to_csv(f'{to_path_base}_valid.csv', header=None, index=False)
    return frame

In [7]:
fix_file('../data/logos.csv', '../data/logos')

               0
0     100060.jpg
1     100061.jpg
2     100080.jpg
3     100085.jpg
4     100096.jpg
..           ...
242  1000560.jpg
243  1000561.jpg
244  1000562.jpg
245  1000563.jpg
246  1000564.jpg

[247 rows x 1 columns]

In [8]:
fix_file('../data/text_only.csv', '../data/text')

               0
0     100092.jpg
1    1000001.jpg
2    1000002.jpg
3    1000009.jpg
4    1000010.jpg
..           ...
232  1000552.jpg
233  1000553.jpg
234  1000556.jpg
235  1000558.jpg
236  1000559.jpg

[237 rows x 1 columns]