In [4]:
import os
import pandas as pd

In [5]:
def fix_file(path, to_path):
    frame = pd.read_csv(path, sep=' ', header=None, index_col=None)
    frame = frame.transpose().map(lambda p: os.path.basename(p))
    frame.to_csv(to_path, header=None, index=False)
    return frame

In [6]:
fix_file('../data/logos.csv', '../data/logos_post.csv')

               0
0     100060.jpg
1     100061.jpg
2     100080.jpg
3     100085.jpg
4     100096.jpg
..           ...
118  1000256.jpg
119  1000259.jpg
120  1000262.jpg
121  1000264.jpg
122  1000266.jpg

[123 rows x 1 columns]

In [7]:
fix_file('../data/text_only.csv', '../data/text_post.csv')

               0
0     100092.jpg
1    1000001.jpg
2    1000002.jpg
3    1000009.jpg
4    1000010.jpg
..           ...
107  1000261.jpg
108  1000263.jpg
109  1000265.jpg
110  1000267.jpg
111  1000268.jpg

[112 rows x 1 columns]